spring:
  application:
    name: sensor-service
  datasource:
    url: jdbc:postgresql://swvs-db-service-a.i.aivencloud.com:14313/defaultdb?sslmode=require
    username: avnadmin
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Ensure other services (like API Gateway) use this instance's IP address rather than
    # a potentially non-resolvable hostname (e.g., DESKTOP-XXXX.mshome.net)
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

application:
  security:
    jwt:
      secret-key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
      expiration: 3600000 # Token validity duration in milliseconds (e.g., 1 hour)

